### ISSUE TITLE
Requirements for listing the app in Contentful's App Marketplace

### ISSUE THREAD

**Issue by jesseday** [adaptdk/adapt-essentials-color-picker#4]
- [x] License agreement
- [x] Link to privacy policy
- [x] Every app should be thoroughly documented, covering installation, configuration, and usage
- [x] #6
- [x] Review your app using manual or automated tools to ensure that you are using up to date packages (if used) and that your app has no known vulnerabilities
  - Let's setup dependabot
- [x] Ensure that the permissions required by the app are reasonable. For example, an app doing translations should not need access to users or data about other spaces
- [x] Ensure that the UI/UX of the app:
    * Looks and feels like Contentful, using [Forma36](https://f36.contentful.com/) styled components wherever possible
    * Does not “break” the surrounding Contentful experience. For example, iFrames or overlays should not unexpectedly hide or cover other features
    * Fits simply into the Contentful experience. Avoid unnecessary complexity or steps if possible.
- [x] Apps should be reviewed for typos or grammatical issues before submission
- [x] A clear name for your app - generally your business/product name
- [x] A tagline, description, feature list, and requirements list for your app
- [x] Logo(s) and screenshots - these will be used in the Marketplace, on your developer page, as well as in the technology partner page

**Comment by jesseday** [comment]
Privacy policy - apparently we need one.  Maybe it could be as simple as "This app does not collect any personal information".

**Comment by jesseday** [comment]
>  Every app must include a support email or link where a user can request support or ask questions about the app

We should link to the issues in this repo

**Comment by jesseday** [comment]
>  A clear name for your app - generally your business/product name

What about something like "Adapt Essentials Toolkit: Color Picker".  Feels awkward without other apps out there, but the desire is that we would have more

**Comment by Toxicom** [comment]
> Privacy policy - apparently we need one. Maybe it could be as simple as "This app does not collect any personal information".
> 
> Edit:
> 
> I found an app that is similar in scope to ours, eg it shouldn't be processing anyone's information, and it does have this privacy policy. They do mention that they capture an email address though. https://www.prototyp.se/privacy-policy/conditional-fields-app

Where should this privacy policy be stored? Inside the repository? Adapt's website?

**Comment by Toxicom** [comment]
> > Every app should be thoroughly documented, covering installation, configuration, and usage
> 
> I think we probably need to add information about how to configure a color picker field. Eg, add a JSON field, choose the color picker widget, and configure colors.
> 
> We should probably also get rid of the How To Use readme section if this is going to be in the Contentful marketplace since installation won't require any code. If you want to keep that info, maybe it could move it to a CONTRIBUTING.md file

We really do need instructions, JSON field would not work! 😄 Where do you think should this information be stored? In the configuration screen? Or the landing page for the configuration screen that you come to from the martketplace? If it's the latter, when/how do we add that info?

**Comment by Toxicom** [comment]
> > Every app must include a support email or link where a user can request support or ask questions about the app
> 
> We should link to the issues in this repo

I'll set up some issue templates

**Comment by Toxicom** [comment]
> > A clear name for your app - generally your business/product name
> 
> What about something like "Adapt Essentials Toolkit: Color Picker".
> 
> Other potential variations
> 
> * Adapt Toolkit: Color Picker
> * Adapt Essentials: Color Picker
> * Adapt Toolkit: Design Tokens
> * Adapt Toolkit: Color Tokens
> * Design Tokens
> * Color Tokens

Out of these I like **Adapt Esentials: Color Picker** except that I feel like this is more than *just* a color picker. What about a simpler name - **Adapt Essentials: Colors**?

**Comment by Toxicom** [comment]
> Review your app using manual or automated tools to ensure that you are using up to date packages (if used) and that your app has no known vulnerabilities
Let's setup dependabot

I *think* dependabot's already setup? At least I see a PR opened by it: https://github.com/adaptdk/contentful-color-app/pull/2

**Comment by Toxicom** [comment]
> Ensure that the UI/UX of the app:
Looks and feels like Contentful, using [Forma36](https://f36.contentful.com/) styled components wherever possible
Does not “break” the surrounding Contentful experience. For example, iFrames or overlays should not unexpectedly hide or cover other features
Fits simply into the Contentful experience. Avoid unnecessary complexity or steps if possible.

I feel like this is also done ✅ I'm using Forma36 components and where I'm not, I'm using the style tokens exposed by it.

**Comment by Toxicom** [comment]
> Logo(s) and screenshots - these will be used in the Marketplace, on your developer page, as well as in the technology partner page

I guess we need to reach out to Jessamine or Corinne. I've done some quick sketches of how I imagine the logo. Now the actual sketches are terrible, I know, but the gist is:
- Variant 1: Adapt logo big in the middle, in the corner color picker
- Variant 2: reversed, color picker middle, adapt logo corner

The reasoning for this is since it's part of the Adapt Essentials, later down the line when we have more products, they could have similar logo format and therefore be easily recognisable. Looking at this longer, I like variant 1 more, especially since the name of the app would start with **Adapt** most likely
![var1](https://github.com/adaptdk/contentful-color-app/assets/69549795/fbaeba4f-f173-4bb1-ae8f-14ae50e5eb91)
![var2](https://github.com/adaptdk/contentful-color-app/assets/69549795/35539f4e-b90b-4c66-9f76-6ef0396b68ca)

**Comment by Toxicom** [comment]
>  Apps should be reviewed for typos or grammatical issues before submission

Looks good to me, reviewed it several times while developing and also after. I'd cross this off as completed, but perhaps will wait for at least one full reviewal of the app itself

**Comment by jesseday** [comment]
> We really do need instructions, JSON field would not work! 😄 Where do you think should this information be stored? In the configuration screen? Or the landing page for the configuration screen that you come to from the martketplace? If it's the latter, when/how do we add that info?

😄 I was thinking the readme would work

**Comment by Toxicom** [comment]
> Link to privacy policy

Waiting for #12 

> Every app should be thoroughly documented, covering installation, configuration, and usage

I think #12 should accomplish that

>  Ensure that the permissions required by the app are reasonable. For example, an app doing translations should not need access to users or data about other spaces

My mind is going blank here, when/where do we set up permissions?

>  A clear name for your app - generally your business/product name

Looks like it's decided as `Adapt Toolkit: Color Tokens`, although I still prefer `Adapt Essentials: Colors` 😆 

> A tagline, description, feature list, and requirements list for your app

See comment https://github.com/adaptdk/adapt-toolkit-color-picker/issues/11#issuecomment-1715545761

> Logo(s) and screenshots - these will be used in the Marketplace, on your developer page, as well as in the technology partner page

See comment https://github.com/adaptdk/adapt-toolkit-color-picker/issues/10#issuecomment-1715599712

**Comment by jesseday** [comment]
> My mind is going blank here, when/where do we set up permissions?

I'm guessing there may not be particular permissions required for this app.  I kept that in just to make sure, but if you don't know then we're good.

> Looks like it's decided as Adapt Toolkit: Color Tokens, although I still prefer Adapt Essentials: Colors 😆

Oh man, I don't care that much.  I like `Adapt Essentials: Colors`
